---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install lxml
      command: apt-get install python3-lxml 
      environment:
      CFLAGS: "-O0"
 
    - name: Creates directory
      file:
          path: /home/springboot
          state: directory
          owner: adminuser
          group: adminuser
          mode: 777
    - maven_artifact:
          group_id: com.strikers
          artifact_id: mediclaim
          repository_url: 'http://20.55.48.213:8081/repository/maven-snapshots/'
          username: admin
          password: admin123
          dest: /home/springboot/
          keep_name: yes
