---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install lxml requirements
      apt: "pkg={{ item }} state=present update_cache=yes"
      sudo: yes
      with_items:
       - python-dev
       - libxml2
       - libxml2-dev
       - libxslt1-dev
       - lib32z1-dev
       - libssl-dev
       - zlib1g-dev

    - name: install lxml
      command: "{{ path/to/virtualenv/bin/ }}pip install lxml"
      environment:
      CFLAGS: "-O0"
 
    - name: Creates directory
      file:
          path: /home/springboot
          state: directory
          owner: adminuser
          group: adminuser
          mode: 777
    - maven_artifact:
          group_id: com.strikers
          artifact_id: mediclaim
          repository_url: 'http://20.55.48.213:8081/repository/maven-snapshots/'
          username: admin
          password: admin123
          dest: /home/springboot/
          keep_name: yes
